all: skittles greedy chart

skittles: skittles.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o skittles skittles.c -lcs50 -lm
	
greedy: greedy.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o greedy greedy.c -lcs50 -lm
	
chart: chart.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -o chart chart.c -lcs50 -lm
